cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove,
         name='cart_remove'),
    
]

magazgleb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', include('main.urls', namespace='main')), 
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views

app_name = 'main'  

urlpatterns = [
    path('', views.popular_list, name='popular_list'),
    path('shop/', views.product_list, name='product_list'),
    path('shop/<slug:slug>/', views.product_detail, 
         name='product_detail'),
     path('shop/category/<slug:category_slug>/', views.product_list,
         name='product_list_by_category'),
]

cart/models.py
from django.db import models

# Create your models here.

main/models.py
from dataclasses import fields
from turtle import mode
from unicodedata import category
from zoneinfo import available_timezones
from django.db import models
from django.urls import reverse 


class Category(models.Model): 
    name = models.CharField(max_length=20, 
                            unique=True)
    slug = models.SlugField(max_length=20, 
                            unique=True)
    
    
    class Meta:
        ordering = ['name']
        indexes = [models.Index(fields=['name'])]
        verbose_name = 'category'
        verbose_name_plural = 'categories'
        
        
    def get_absolute_url(self):
        return reverse('main:product_list_by_category',
                       args=[self.slug])
    
    
    
    def __str__(self):
        return self.name
    
    
    
class Product(models.Model):
    category = models.ForeignKey(Category, 
                                 related_name='products', 
                                 on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    slug = models.SlugField(max_length=50)
    image = models.ImageField(upload_to='products/%Y/%m/%d',
                              blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10,
                                decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    discount = models.DecimalField(default=0.00, max_digits=4, 
                                   decimal_places=2)
    
    class Meta:
        ordering = ['name']
        indexes = [
            models.Index(fields=['id', 'slug']),
            models.Index(fields=['name']),
            models.Index(fields=['-created']),
        ]    
        
    def __str__(self):
        return self.name
    
    
    def get_absolute_url(self):
        return reverse("main:product_detail", kwargs={'slug': self.slug})

    
    
    def sell_price(self):
        if self.discount:
            return round(self.price - self.price * self.discount / 100, 2)
        return self.price

cart/forms.py
from typing import override
from django import forms 


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 11)]


class CartAddProductFrom(forms.Form):
    quantity = forms.TypedChoiceField(
        choices=PRODUCT_QUANTITY_CHOICES,
        coerce=int
    )
    override = forms.BooleanField(required=False,
                                  initial=False,
                                  widget=forms.HiddenInput)
    

cart/views.py
import re
from django.shortcuts import render, redirect, \
    get_object_or_404
from django.views.decorators.http import require_POST
from main.models import Product
from .cart import Cart
from .forms import CartAddProductFrom


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductFrom(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 override_quantity=cd['override'])
        
    return redirect('cart:cart_detail')


@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    return render(request, 'cart/detail.html', {'cart': cart})

main/views.py
# myapp/views.py
from itertools import product
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator
from .models import Product, Category

def popular_list(request):
    products = Product.objects.filter(available=True)[:3]
    return render(request,
                  'main/index/index.html',
                  {'products': products})
    
def product_detail(request, slug):
    product = get_object_or_404(Product,
                                slug=slug,
                                available=True)
    return render(request, 
                  'main/product/detail.html',
                  {'product': product})



def product_list(request, category_slug=None):
    page = request.GET.get('page', 1)
    category = None 
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    paginator = Paginator(products, 10)
    current_page = paginator.page(int(page))
    if category_slug:
        category = get_object_or_404(Category,
                                     slug=category_slug)
        paginator = Paginator(products.filter(category=category), 10)
        products = products.filter(category=category)
        current_page = paginator.page(int(page))
    return render(request,
                  'main/product/list.html',
                  {'category': category,
                   'categories': categories,
                   'products': current_page,
                   'slug_url': category_slug})
    

cart/templates/cart/detail.html
{% extends "main/base.html" %}
{% load static %}

{% block title %}Cart{% endblock title %}

{% block content %}
    <section class="cart d-flex">
        <div class="cart-title">
            <h2>Shopping Cart</h2>
        </div>
        <div class="cart-cards">
            {% for item in cart %}
                {% with product=item.product %}
                    <div class="cart-card d-flex">
                        <div class="cart-card-img">
                            <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/noimage.jpg' %}{% endif %}" alt="">
                        </div>
                        <div class="cart-card-info">
                            <div class="cart-card-name">
                                <p>{{ product.name }}</p>
                            </div>
                            <div class="cart-card-q">
                                <p>Quantity: {{ item.quantity }}</p>
                            </div>
                        </div>
                        <form action="{% url "cart:cart_remove" product.id %}" method="post">
                            <input type="submit" value="Remove" class="remove-btn">
                            {% csrf_token %}
                        </form>
                        <div class="cart-card-price">
                        {% if product.discount %}
                                <div class="cart-discount d-flex gap-2">
                                     <p class="line">$ {{ product.price }}</p>
                                    <p>$ {{ product.sell_price }}</p>
                                 </div>
                            {% else %}
                                <p class="price">$ {{ product.price }}</p>
                             {% endif %}
                        </div>
                    </div>
                {% endwith %}
            {% endfor %}
        </div>
        <div class="total">
            <h5>Total sum: $ {{ cart.get_total_price }} </h5>
        </div>
        <div class="cart-buttons d-flex gap-3">
            <a href="/shop" class="cart-btn">Continue shopping</a>
            <a href="#" class="cart-btn">Checkout</a>
        </div>
    </section>
{% endblock content %}

main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>

    {% comment %} bootstrap {% endcomment %}
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    
    {% comment %} css {% endcomment %}
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="icon" href="{% static 'img/favicon.ico' %}" type="image/x-icon">
</head>
<body>
    <header class="header sticky-top">
        <div class="header-container d-flex">
            <nav class="header-nav pt-4">
                <ul class="header-list d-flex">
                    <li>
                        <a href="/" class="nav-a m-3">Home</a>
                    </li>
                    <li>
                        <a href="#" class="nav-a m-3">Shop</a>
                    </li>
                </ul>
            </nav>
            <div class="header-logo">
                <a href="/"><img src="{% static 'img/qwewqe.png' %}" alt="Company Logo" class="heavy-logo"></a>
            </div>
            <div class="header-profile">
                <a href="#" class="m-3">LOGIN</a>
            </div> 
        </div>
    </header>
    <div class="container">
        {% block content %}
        {% endblock content %}
    </div>
    <img src="{% static 'img/frame1.png' %}" class="frame1" alt="Frame 1">
    <img src="{% static 'img/frame2.png' %}" class="frame2" alt="Frame 2">
    <img src="{% static 'img/frame3.png' %}" class="frame3" alt="Frame 3">
    <img src="{% static 'img/frame4.png' %}" class="frame4" alt="Frame 4">

    {% comment %} js for bootstrap {% endcomment %}
    <script src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

main/templates/main/index/index.html
{% extends "main/base.html" %}
{% load static %}

{% block title %}Home{% endblock title %}

{% block content %}
    <section class="home d-flex flex-column">
        <div class="home-title d-flex flex-column align-items-center">
            <a href="#" class="home-btn mt-4">ALL PRODUCTS</a>
        </div>
        <div class="home-recomendation">
            <div class="rec-title mb-4">
                <h3><span>Popular Accessories</span></h3>
            </div>
        </div>
        <div class="home-cards d-flex gap-4">
            {% for product in products %}
                <a href="{{ product.get_absolute_url }}" class="home-card d-flex flex-column align-items-center text-center">
                    <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/noimage.jpg' %}{% endif %}" alt="Product Image" class="card-img" alt="">
                    <h5 class="title-card">{{ product.name }}</h5>
                    {% if product.discount %}
                        <div class="cate-discount d-flex gap-2">
                            <p class="line">{{ product.price }}</p>
                            <p>{{ product.sell_price }}</p>
                        </div>
                    {% else %}
                        <p class="price">{{ product.price }}</p>
                    {% endif %}
                </a>
            {% endfor %}
        </div>
    </section>
    <img src="{% static 'img/logogot.png' %}" class="logogothic" alt="Logo">
    <img src="{% static 'img/subtitlee.png' %}" class="subtitlee" alt="Subtitle">
{% endblock content %}

main/templates/main/product/detail.html
{% extends "main/base.html" %}
{% load static %}

{% block title %}
    {{ product.name }}
{% endblock title %}

{% block content %}
    <div class="detail-product d-flex">
        <div class="detail-img">
            <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/noimage.jpg' %}{% endif %}" alt="" class="detail-image">
        </div>
        <div class="detail-description">
            <h2>{{ product.name }}</h2>
            <h3>Category: {{ product.category }}</h3>
            <p>Description: {{ product.description|linebreaks }}</p>
            {% if product.discount %}
                <div class="cart-discount d-flex gap-2">
                    <p class="line">$ {{ product.price }}</p>
                    <p>$ {{ product.sell_price }}</p>
                </div>
            {% else %}
                <p class="price">$ {{ product.price }}</p>
            {% endif %}
            <form action="{% url "cart:cart_add" product.id %}" class="qform" method="post">
                <div class="cart-form">
                    {{ cart_product_form }}
                    {% csrf_token %}
                </div>
                <input type="submit" class="add-to-cart-btn" value="Add to cart">
            </form>
        </div> 
    </div>
{% endblock content %}

main/templates/main/product/list.html
{% extends "main/base.html" %}
{% load static %}

{% block title %}Shop{% endblock title %}

{% block content %}
    <div class="llist d-flex">
        <div class="sidebar">
            <h3>Categories</h3>
            <ul>
                <li {% if not category %}class='selected'{% endif %}>
                    <a href="{% url "main:product_list" %}">All</a>
                </li>
                {% for c in categories %}
                    <li {% if category.slug == c.slug %}class='selected'{% endif %}>
                        <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
                    </li>
                {% endfor %}
            </ul>
        </div>
        <div class="main">
            <div class="main-title">
                {% if category %}{{ category.name }}{% else %}Products{% endif %}
            </div>
            <div class="product-list">
                <div class="items">
                    {% for product in products %}
                        <div class="item">
                            <a href="{{ product.get_absolute_url }}" class="home-card d-flex flex-column align-items-center text-center">
                                <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/noimage.jpg' %}{% endif %}" class='card-img' alt="">
                                <h5 class="title-card">{{ product.name }}</h5>
                                    {% if product.discount %}
                                    <div class="cart-discount d-flex gap-2">
                                        <p class="line">$ {{ product.price }}</p>
                                        <p>$ {{ product.sell_price }}</p>
                                    </div>
                                {% else %}
                                    <p class="price">$ {{ product.price }}</p>
                                {% endif %}
                            </a>
                        </div>
                    {% endfor %}
                </div>
            </div>
            <ul class="pagination">
                <li class="{% if not products.has_previous %}disabled{% endif %}">
                    <a href="{% if products.has_previous %}?page={{ products.previous_page_number}}{% endif %}">Previous</a>
                </li>
                {% for page in products.paginator.page_range %}
                    {% if page >= products.number|add:-2 and page <= products.number|add:2 %}
                        <li>
                            <a href="?page={{ page }}" class="{% if products.number == page %}disabled{% endif %}">{{ page }}</a>
                        </li>
                    {% endif %}
                {% endfor %}
                <li class="{% if not products.has_next %}disabled{% endif %}">
                    <a href="{% if products.has_next %}?page={{ products.next_page_number}}{% endif %}">Next</a>
                </li>
            </ul>
        </div>
    </div>
{% endblock content %}